# Generated by Django 5.2 on 2025-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(blank=True, default='0000000000', max_length=12, null=True),
        ),
    ]
