# Generated by Django 5.2 on 2025-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_available_time_doctor_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_no',
            field=models.CharField(blank=True, default='0000000000', max_length=12, null=True),
        ),
    ]
